/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  // But you can create a sidebar manually
  /*
  tutorialSidebar: [
    'intro',
    'hello',
    {
      type: 'category',
      label: 'Tutorial',
      items: ['tutorial-basics/create-a-document'],
    },
  ],
   */
};

//module.exports = sidebars;

module.exports = {
  mySideBar:[
    'intro',
    'toDoList',
    'toDoListLEGACY',
    {
      type: 'category',
      label: 'TryHackMe',
      link: {
        type: 'doc',
        id: 'TryHackMe/introduction',
      },
      items: [
          {
            type: 'category',
            label: 'Advent Of Cyber 2021',
            link: {
              type: 'generated-index',
            },
            items: [
              {
                type: 'category',
                label: 'Days 1-7 ~ Web Exploitation',
                link: {
                  type: 'generated-index',
                },
                items: [
                  'TryHackMe/Advent-Of-Cyber-2021/Modules/Days 1-7 ~ Web Exploitation/Advent of Cyber 2021 Day 1',
                  'TryHackMe/Advent-Of-Cyber-2021/Modules/Days 1-7 ~ Web Exploitation/Advent of Cyber 2021 Day 2',
                  'TryHackMe/Advent-Of-Cyber-2021/Modules/Days 1-7 ~ Web Exploitation/Advent of Cyber 2021 Day 3',
                  'TryHackMe/Advent-Of-Cyber-2021/Modules/Days 1-7 ~ Web Exploitation/Advent of Cyber 2021 Day 4',
                  'TryHackMe/Advent-Of-Cyber-2021/Modules/Days 1-7 ~ Web Exploitation/Advent of Cyber 2021 Day 5',
                  'TryHackMe/Advent-Of-Cyber-2021/Modules/Days 1-7 ~ Web Exploitation/Advent of Cyber 2021 Day 6',
                  'TryHackMe/Advent-Of-Cyber-2021/Modules/Days 1-7 ~ Web Exploitation/Advent of Cyber 2021 Day 7',
                ],
              },
              'TryHackMe/Advent-Of-Cyber-2021/Modules/Day 8 ~ Special By Joyn Hammond/Advent of Cyber Day 8', //just realized a folder here wasn't necessary
              {
                type: 'category',
                label: 'Days 9-14 ~ Networking',
                link: {
                  type: 'generated-index',
                },
                items: [
                  'TryHackMe/Advent-Of-Cyber-2021/Modules/Days 9-14 ~ Networking/Advent of Cyber 2021 Day 9',
                  'TryHackMe/Advent-Of-Cyber-2021/Modules/Days 9-14 ~ Networking/Advent of Cyber 2021 Day 10',
                  'TryHackMe/Advent-Of-Cyber-2021/Modules/Days 9-14 ~ Networking/Advent of Cyber 2021 Day 11',
                  'TryHackMe/Advent-Of-Cyber-2021/Modules/Days 9-14 ~ Networking/Advent of Cyber 2021 Day 12',
                  'TryHackMe/Advent-Of-Cyber-2021/Modules/Days 9-14 ~ Networking/Advent of Cyber 2021 Day 13',
                  'TryHackMe/Advent-Of-Cyber-2021/Modules/Days 9-14 ~ Networking/Advent of Cyber 2021 Day 14',
                ],
              },
              'TryHackMe/Advent-Of-Cyber-2021/Modules/Advent of Cyber 2021 Day 16',
              {
                type: 'category',
                label: 'Days 17-18 ~ Cloud',
                link: {
                  type: 'generated-index',
                },
                items: [
                  'TryHackMe/Advent-Of-Cyber-2021/Modules/Days 17-18 ~ Cloud/Advent of Cyber 2021 Day 17',
                  'TryHackMe/Advent-Of-Cyber-2021/Modules/Days 17-18 ~ Cloud/Advent of Cyber 2021 Day 18',
                ],
              },
              {
                type: 'category',
                label: 'Days 19-23 ~ Blue Teaming',
                link: {
                  type: 'generated-index',
                },
                items: [
                  'TryHackMe/Advent-Of-Cyber-2021/Modules/Days 19-24 ~ Blue Teaming/Advent of Cyber 2021 Day 19',
                  'TryHackMe/Advent-Of-Cyber-2021/Modules/Days 19-24 ~ Blue Teaming/Advent of Cyber 2021 Day 20',
                  'TryHackMe/Advent-Of-Cyber-2021/Modules/Days 19-24 ~ Blue Teaming/Advent of Cyber 2021 Day 21',
                  'TryHackMe/Advent-Of-Cyber-2021/Modules/Days 19-24 ~ Blue Teaming/Advent of Cyber 2021 Day 22',
                  'TryHackMe/Advent-Of-Cyber-2021/Modules/Days 19-24 ~ Blue Teaming/Advent of Cyber 2021 Day 23',
                ],
              },
              'TryHackMe/Advent-Of-Cyber-2021/Modules/Advent of Cyber 2021 Day 24',
            ],   
          },
          {
            type: 'category',
            label: 'Free Path',
            link: {
              type: 'doc',
              id: 'TryHackMe/Free-Path/Free_Path',
            },
            items: [
              {
                type: 'category',
                label: 'Level 1',
                link: {
                  type: 'generated-index',
                },
                items: [
                  'TryHackMe/Free-Path/Level 1/Tutorial',
                  'TryHackMe/Free-Path/Level 1/Intro-To-Offensive-Security',
                  {
                    type: 'category',
                    label: 'Introduction to Pentesting',
                    link: {
                      type: 'generated-index',
                    },
                    items: [
                      'TryHackMe/Free-Path/Level 1/Intro to Offensive Pentesting/pentesting-fundamentals',
                      'TryHackMe/Free-Path/Level 1/Intro to Offensive Pentesting/principles-of-security',
                    ],
                  },
                  {
                    type: 'category',
                    label: 'Linux Fundamentals',
                    link: {
                      type: 'generated-index',
                    },
                    items: [
                      'TryHackMe/Free-Path/Level 1/Linux Fundamentals/linux-fundamentals-1',
                      'TryHackMe/Free-Path/Level 1/Linux Fundamentals/linux-fundamentals-2',
                      'TryHackMe/Free-Path/Level 1/Linux Fundamentals/linux-fundamentals-3',
                    ],
                  },
                  'TryHackMe/Free-Path/Level 1/OHsint',
                ],
                
              },
              {
                type: 'category',
                label: 'Level 2',
                link: {
                  type: 'generated-index',
                },
                items: [
                  
                ],
              },

            ],
          },
      ],
    },
    //'intro', testing sidebar added other stuff (will do eventually later on
  ],
};
